# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.docket_entry_attachments_inner import DocketEntryAttachmentsInner

class TestDocketEntryAttachmentsInner(unittest.TestCase):
    """DocketEntryAttachmentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocketEntryAttachmentsInner:
        """Test DocketEntryAttachmentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocketEntryAttachmentsInner`
        """
        model = DocketEntryAttachmentsInner()
        if include_optional:
            return DocketEntryAttachmentsInner(
                recap_id = 56,
                pacer_url = '',
                description = '',
                attachment_number = 56
            )
        else:
            return DocketEntryAttachmentsInner(
        )
        """

    def testDocketEntryAttachmentsInner(self):
        """Test DocketEntryAttachmentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
