# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.case import Case

class TestCase(unittest.TestCase):
    """Case unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Case:
        """Test Case
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Case`
        """
        model = Case()
        if include_optional:
            return Case(
                attorney_orgs = [
                    ''
                    ],
                available_documents = [
                    ''
                    ],
                case_defendants = [
                    openapi_client.models.defendant.Defendant(
                        name = '', 
                        institution = '', 
                        institution_city = '', 
                        institution_county = '', 
                        institution_alt_state = '', 
                        defendant_level = '', 
                        defendant_level_other = '', )
                    ],
                case_documents = [
                    openapi_client.models.document.Document(
                        date = '', 
                        date_is_estimate = True, 
                        date_not_available = True, 
                        description = '', 
                        document_source = '', 
                        document_type = '', 
                        order_type = '', 
                        citation_paren = '', 
                        cite_1_page = 56, 
                        cite_1_reporter = '', 
                        cite_1_vol = 56, 
                        cite_2_page = 56, 
                        cite_2_reporter = '', 
                        cite_2_vol = 56, 
                        cite_3_page = 56, 
                        cite_3_reporter = '', 
                        cite_3_vol = 56, 
                        citation_status = '', 
                        court = '', 
                        no_title = True, 
                        party_types = [
                            ''
                            ], 
                        per_curium = True, 
                        is_core_document = True, 
                        file = '', 
                        title = '', 
                        public_note = '', 
                        document_type_other = '', 
                        external_url = '', 
                        ecf_number = '', 
                        clearinghouse_link = '', 
                        id = 56, 
                        document_status = '', )
                    ],
                case_dockets = [
                    openapi_client.models.docket.Docket(
                        id = 56, 
                        docket_number_manual = '', 
                        docket_office_number = '', 
                        docket_year = 56, 
                        docket_case_type = '', 
                        docket_filing_number = 56, 
                        court = '', 
                        state = '', 
                        is_main_docket = True, 
                        recap_link = '', 
                        docket_entries = [
                            openapi_client.models.docket_entry.DocketEntry(
                                row_number = 56, 
                                entry_number = '', 
                                date_filled = '', 
                                description = '', 
                                attachments = [
                                    openapi_client.models.docket_entry_attachments_inner.DocketEntry_attachments_inner(
                                        recap_id = 56, 
                                        pacer_url = '', 
                                        description = '', 
                                        attachment_number = 56, )
                                    ], 
                                url = '', 
                                recap_pdf_url = '', 
                                pacer_doc_id = '', 
                                id = 56, )
                            ], 
                        scales_html = '', )
                    ],
                case_resources = [
                    openapi_client.models.resource.Resource(
                        file = '', 
                        title = '', 
                        author_role = '', 
                        abstract = '', 
                        author = '', 
                        institution = '', 
                        citation = '', 
                        external_url = '', 
                        display_date = '', 
                        resource_type = [
                            ''
                            ], 
                        cases = [
                            ''
                            ], 
                        case_types = [
                            ''
                            ], 
                        date = '', 
                        causes = [
                            ''
                            ], 
                        issues = [
                            ''
                            ], 
                        special_collections = [
                            ''
                            ], 
                        attorney_orgs = [
                            ''
                            ], 
                        source = '', )
                    ],
                case_ongoing = '',
                case_status = '',
                case_types = [
                    ''
                    ],
                cause_other = '',
                causes = [
                    ''
                    ],
                class_action_granted = '',
                class_action_sought = '',
                closing_year = 56,
                court = '',
                custom_issues = [
                    ''
                    ],
                defendant_payment = '',
                docket_status = '',
                filing_date = '',
                filing_year = 56,
                id = 56,
                injuction_duration = 56,
                issues = [
                    ''
                    ],
                last_checked_date = '',
                main_docket = openapi_client.models.docket.Docket(
                    id = 56, 
                    docket_number_manual = '', 
                    docket_office_number = '', 
                    docket_year = 56, 
                    docket_case_type = '', 
                    docket_filing_number = 56, 
                    court = '', 
                    state = '', 
                    is_main_docket = True, 
                    recap_link = '', 
                    docket_entries = [
                        openapi_client.models.docket_entry.DocketEntry(
                            row_number = 56, 
                            entry_number = '', 
                            date_filled = '', 
                            description = '', 
                            attachments = [
                                openapi_client.models.docket_entry_attachments_inner.DocketEntry_attachments_inner(
                                    recap_id = 56, 
                                    pacer_url = '', 
                                    description = '', 
                                    attachment_number = 56, )
                                ], 
                            url = '', 
                            recap_pdf_url = '', 
                            pacer_doc_id = '', 
                            id = 56, )
                        ], 
                    scales_html = '', ),
                name = '',
                never_filed = True,
                non_docket_case_number = '',
                non_docket_case_number_type = '',
                non_docket_case_number_type_other = '',
                order_end_year = 56,
                order_start_year = 56,
                permanent_injuction = True,
                plaintiff_description = '',
                prevailing_party = '',
                pro_se_status = '',
                public_interest_lawyer = '',
                relief_natures = [
                    ''
                    ],
                relief_nature_other = '',
                relief_sources = [
                    ''
                    ],
                settlement_agreement = [
                    ''
                    ],
                settlement_judgment_date = '',
                settlement_judgment_year = 56,
                special_collections = [
                    ''
                    ],
                state = '',
                summary = '',
                summary_published_date = '',
                summary_short = '',
                summary_tiny = '',
                terminating_date = '',
                clearinghouse_link = '',
                is_action = True,
                plaintiff_type = [
                    openapi_client.models.case_plaintiff_type_inner.Case_plaintiff_type_inner(
                        value = '', )
                    ],
                defendant_type = [
                    openapi_client.models.case_plaintiff_type_inner.Case_plaintiff_type_inner(
                        value = '', )
                    ],
                facility_type = [
                    openapi_client.models.case_plaintiff_type_inner.Case_plaintiff_type_inner(
                        value = '', )
                    ],
                constitutional_clause = [
                    openapi_client.models.case_plaintiff_type_inner.Case_plaintiff_type_inner(
                        value = '', )
                    ],
                special_case_type = [
                    openapi_client.models.case_plaintiff_type_inner.Case_plaintiff_type_inner(
                        value = '', )
                    ],
                content_of_injunction = [
                    openapi_client.models.case_plaintiff_type_inner.Case_plaintiff_type_inner(
                        value = '', )
                    ]
            )
        else:
            return Case(
        )
        """

    def testCase(self):
        """Test Case"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
