# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document import Document

class TestDocument(unittest.TestCase):
    """Document unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Document:
        """Test Document
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Document`
        """
        model = Document()
        if include_optional:
            return Document(
                var_date = '',
                date_is_estimate = True,
                date_not_available = True,
                description = '',
                document_source = '',
                document_type = '',
                order_type = '',
                citation_paren = '',
                cite_1_page = 56,
                cite_1_reporter = '',
                cite_1_vol = 56,
                cite_2_page = 56,
                cite_2_reporter = '',
                cite_2_vol = 56,
                cite_3_page = 56,
                cite_3_reporter = '',
                cite_3_vol = 56,
                citation_status = '',
                court = '',
                no_title = True,
                party_types = [
                    ''
                    ],
                per_curium = True,
                is_core_document = True,
                file = '',
                title = '',
                public_note = '',
                document_type_other = '',
                external_url = '',
                ecf_number = '',
                clearinghouse_link = '',
                id = 56,
                document_status = ''
            )
        else:
            return Document(
        )
        """

    def testDocument(self):
        """Test Document"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
