# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.defendant import Defendant

class TestDefendant(unittest.TestCase):
    """Defendant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Defendant:
        """Test Defendant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Defendant`
        """
        model = Defendant()
        if include_optional:
            return Defendant(
                name = '',
                institution = '',
                institution_city = '',
                institution_county = '',
                institution_alt_state = '',
                defendant_level = '',
                defendant_level_other = ''
            )
        else:
            return Defendant(
        )
        """

    def testDefendant(self):
        """Test Defendant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
