# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.docket import Docket

class TestDocket(unittest.TestCase):
    """Docket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Docket:
        """Test Docket
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Docket`
        """
        model = Docket()
        if include_optional:
            return Docket(
                id = 56,
                docket_number_manual = '',
                docket_office_number = '',
                docket_year = 56,
                docket_case_type = '',
                docket_filing_number = 56,
                court = '',
                state = '',
                is_main_docket = True,
                recap_link = '',
                docket_entries = [
                    openapi_client.models.docket_entry.DocketEntry(
                        row_number = 56, 
                        entry_number = '', 
                        date_filled = '', 
                        description = '', 
                        attachments = [
                            openapi_client.models.docket_entry_attachments_inner.DocketEntry_attachments_inner(
                                recap_id = 56, 
                                pacer_url = '', 
                                description = '', 
                                attachment_number = 56, )
                            ], 
                        url = '', 
                        recap_pdf_url = '', 
                        pacer_doc_id = '', 
                        id = 56, )
                    ],
                scales_html = ''
            )
        else:
            return Docket(
        )
        """

    def testDocket(self):
        """Test Docket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
