# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.case_plaintiff_type_inner import CasePlaintiffTypeInner

class TestCasePlaintiffTypeInner(unittest.TestCase):
    """CasePlaintiffTypeInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CasePlaintiffTypeInner:
        """Test CasePlaintiffTypeInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CasePlaintiffTypeInner`
        """
        model = CasePlaintiffTypeInner()
        if include_optional:
            return CasePlaintiffTypeInner(
                value = ''
            )
        else:
            return CasePlaintiffTypeInner(
        )
        """

    def testCasePlaintiffTypeInner(self):
        """Test CasePlaintiffTypeInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
