# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.test_get200_response import TestGet200Response

class TestTestGet200Response(unittest.TestCase):
    """TestGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestGet200Response:
        """Test TestGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestGet200Response`
        """
        model = TestGet200Response()
        if include_optional:
            return TestGet200Response(
                message = 'Success, you have access to the Civil Rights Clearinghouse Litigation API!'
            )
        else:
            return TestGet200Response(
        )
        """

    def testTestGet200Response(self):
        """Test TestGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
