# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DocketEntryAttachments(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'recap_id': 'int',
        'pacer_url': 'str',
        'description': 'str',
        'attachment_number': 'int'
    }

    attribute_map = {
        'recap_id': 'recap_id',
        'pacer_url': 'pacer_url',
        'description': 'description',
        'attachment_number': 'attachment_number'
    }

    def __init__(self, recap_id=None, pacer_url=None, description=None, attachment_number=None):  # noqa: E501
        """DocketEntryAttachments - a model defined in Swagger"""  # noqa: E501
        self._recap_id = None
        self._pacer_url = None
        self._description = None
        self._attachment_number = None
        self.discriminator = None
        if recap_id is not None:
            self.recap_id = recap_id
        if pacer_url is not None:
            self.pacer_url = pacer_url
        if description is not None:
            self.description = description
        if attachment_number is not None:
            self.attachment_number = attachment_number

    @property
    def recap_id(self):
        """Gets the recap_id of this DocketEntryAttachments.  # noqa: E501


        :return: The recap_id of this DocketEntryAttachments.  # noqa: E501
        :rtype: int
        """
        return self._recap_id

    @recap_id.setter
    def recap_id(self, recap_id):
        """Sets the recap_id of this DocketEntryAttachments.


        :param recap_id: The recap_id of this DocketEntryAttachments.  # noqa: E501
        :type: int
        """

        self._recap_id = recap_id

    @property
    def pacer_url(self):
        """Gets the pacer_url of this DocketEntryAttachments.  # noqa: E501


        :return: The pacer_url of this DocketEntryAttachments.  # noqa: E501
        :rtype: str
        """
        return self._pacer_url

    @pacer_url.setter
    def pacer_url(self, pacer_url):
        """Sets the pacer_url of this DocketEntryAttachments.


        :param pacer_url: The pacer_url of this DocketEntryAttachments.  # noqa: E501
        :type: str
        """

        self._pacer_url = pacer_url

    @property
    def description(self):
        """Gets the description of this DocketEntryAttachments.  # noqa: E501


        :return: The description of this DocketEntryAttachments.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DocketEntryAttachments.


        :param description: The description of this DocketEntryAttachments.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def attachment_number(self):
        """Gets the attachment_number of this DocketEntryAttachments.  # noqa: E501


        :return: The attachment_number of this DocketEntryAttachments.  # noqa: E501
        :rtype: int
        """
        return self._attachment_number

    @attachment_number.setter
    def attachment_number(self, attachment_number):
        """Sets the attachment_number of this DocketEntryAttachments.


        :param attachment_number: The attachment_number of this DocketEntryAttachments.  # noqa: E501
        :type: int
        """

        self._attachment_number = attachment_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocketEntryAttachments, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocketEntryAttachments):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
