# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    Python Client to Scrapte the University of Michigan Civil Rights Clearinghouse.  Basic installation: ```sh pip install git+https://github.com/calexander/law-data-design-vip.git ``` 

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.docket_entry import DocketEntry
from typing import Optional, Set
from typing_extensions import Self

class Docket(BaseModel):
    """
    A docket lists, in chronological order, every document filed with the court in a case; this also serves as a timeline of events. A docket also includes the judge(s), parties, and lawyers in a case. A docket number is the individual identifier that a court gives to a case. (Some courts use different terms, but the idea is the same.) Docket numbers usually include some or all of the following information, though it can appear in different orders or formats: - The year the case was filed - The type of case (civil, criminal, etc.) - A unique serial number for the case - Information on which courthouse or jurisdiction it was filed in We collect complete docket numbers as they appear on case documents. We also collect the information it contains (year, case type, etc.) in separate fields. Our system is designed around the federal courts' docketing conventions. The fields on our website correspond to the normal format for federal court docket number: 1:18-cv-528 (office:year-case type-filing number). 
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The ID of the docket. This is different from the case ID and unique to the docket.")
    docket_number_manual: Optional[StrictStr] = Field(default=None, description="The complete docket number, as it appears on case documents.")
    docket_office_number: Optional[StrictStr] = Field(default=None, description="For federal courts, the courthouse or division where the case was filed. This will always be a one-digit number.")
    docket_year: Optional[StrictInt] = Field(default=None, description="The year the case was filed. We collect complete years (e.g. 2021, not 21).")
    docket_case_type: Optional[StrictStr] = Field(default=None, description="Usually a 2-character code corresponding to a particular type of case (e.g. \"cv\" = civil; \"cr\" = criminal). Not all dockets will have a case type code.")
    docket_filing_number: Optional[StrictInt] = Field(default=None, description="The unique portion of a docket number. The filing number is generally unique within a given court.")
    court: Optional[StrictStr] = Field(default=None, description="The court where the docket exists. The options are the same as the court field for cases – see [court](https://api.clearinghouse.net/api-reference/objects/case/case-details#court).")
    state: Optional[StrictStr] = Field(default=None, description="The state where the docket's court is located in.")
    is_main_docket: Optional[StrictBool] = Field(default=None, description="If true, the docket is the main docket for the case. This is typically the trial docket where the case was first filed. On the Clearinghouse site, the main docket is displayed first.")
    recap_link: Optional[StrictStr] = Field(default=None, description="A link to a federal court docket in the RECAP Archive. The [RECAP Archive](https://www.courtlistener.com/recap) is a free, searchable collection of millions of federal court documents and dockets.")
    docket_entries: Optional[List[DocketEntry]] = Field(default=None, description="A list of docket entries. See [Docket Entry](https://api.clearinghouse.net/api-reference/objects/docket-entry). Note: Many dockets are available only as a PDF, rather than as a parsed array of docket entries. In those cases, the docket is saved as a document (see [Documents](https://api.clearinghouse.net/api-reference/objects/case/documents)). ")
    scales_html: Optional[StrictStr] = Field(default=None, description="A URL to an HTML file that is a saved version of the PACER HTML header. PACER, which stands for Public Access to Court Electronic Records, is the federal government's electronic system for providing access to federal court records.")
    __properties: ClassVar[List[str]] = ["id", "docket_number_manual", "docket_office_number", "docket_year", "docket_case_type", "docket_filing_number", "court", "state", "is_main_docket", "recap_link", "docket_entries", "scales_html"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Docket from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in docket_entries (list)
        _items = []
        if self.docket_entries:
            for _item_docket_entries in self.docket_entries:
                if _item_docket_entries:
                    _items.append(_item_docket_entries.to_dict())
            _dict['docket_entries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Docket from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "docket_number_manual": obj.get("docket_number_manual"),
            "docket_office_number": obj.get("docket_office_number"),
            "docket_year": obj.get("docket_year"),
            "docket_case_type": obj.get("docket_case_type"),
            "docket_filing_number": obj.get("docket_filing_number"),
            "court": obj.get("court"),
            "state": obj.get("state"),
            "is_main_docket": obj.get("is_main_docket"),
            "recap_link": obj.get("recap_link"),
            "docket_entries": [DocketEntry.from_dict(_item) for _item in obj["docket_entries"]] if obj.get("docket_entries") is not None else None,
            "scales_html": obj.get("scales_html")
        })
        return _obj


