# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.docket_entry_attachments_inner import DocketEntryAttachmentsInner
from typing import Optional, Set
from typing_extensions import Self

class DocketEntry(BaseModel):
    """
    DocketEntry
    """ # noqa: E501
    row_number: Optional[StrictInt] = None
    entry_number: Optional[StrictStr] = None
    date_filled: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    attachments: Optional[List[DocketEntryAttachmentsInner]] = None
    url: Optional[StrictStr] = None
    recap_pdf_url: Optional[StrictStr] = None
    pacer_doc_id: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["row_number", "entry_number", "date_filled", "description", "attachments", "url", "recap_pdf_url", "pacer_doc_id", "id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocketEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocketEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "row_number": obj.get("row_number"),
            "entry_number": obj.get("entry_number"),
            "date_filled": obj.get("date_filled"),
            "description": obj.get("description"),
            "attachments": [DocketEntryAttachmentsInner.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "url": obj.get("url"),
            "recap_pdf_url": obj.get("recap_pdf_url"),
            "pacer_doc_id": obj.get("pacer_doc_id"),
            "id": obj.get("id")
        })
        return _obj


