# coding: utf-8

"""
    Civil Rights Clearinghouse Simple API

    Python Client to Scrapte the University of Michigan Civil Rights Clearinghouse.  Basic installation: ```sh pip install git+https://github.com/calexander/law-data-design-vip.git ``` 

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Resource(BaseModel):
    """
    Resource
    """ # noqa: E501
    file: Optional[StrictStr] = Field(default=None, description="URL to the PDF file of the resource (if applicable). If the resource is a webpage, then")
    title: Optional[StrictStr] = Field(default=None, description="The title of the resource, usually as it appears in the resource itself.")
    author_role: Optional[StrictStr] = Field(default=None, description="Identifies whether a resources was created by a student or faculty member. Used only for pieces published in law reviews or other periodicals. The options are: ***N/A*** - Resource is not a law review article or periodical. ***Faculty*** - Written by a professor. ***Law Student*** - Written by a law student. ***Student*** - Written by a non-law student. ")
    abstract: Optional[StrictStr] = Field(default=None, description="A brief description of the resource. For law review pieces and other periodicals, we copy and paste the abstract into this field. For other kinds of resources we usually copy a representative paragraph or compose a quick description of the resource.")
    author: Optional[StrictStr] = Field(default=None, description="The full name of the author or authors, if they are individuals.")
    institution: Optional[StrictStr] = Field(default=None, description="The author of the resource, if it's an institutional author. The institutional affiliation of an author, if the author is an individual.")
    citation: Optional[StrictStr] = Field(default=None, description="The citation for a resource. Usually used for law review articles or other periodicals.")
    external_url: Optional[StrictStr] = Field(default=None, description="A link to the resource elsewhere on the web.")
    display_date: Optional[StrictStr] = Field(default=None, description="A written version of the date the resource was published or created. This field allows us to differentiate different issues of periodicals (e.g. \"Fall 2021\", \"May 1996\").")
    resource_type: Optional[List[StrictStr]] = Field(default=None, description="We collect a several kinds of resources, which are usually different kinds of things. ***Clearinghouse Links to External Resources*** - Links to other websites with information relevant to a case. For example, an ACLU webpage describing a case it litigated or an Oyez entry for a case heard by the Supreme Court. ***Articles about the Clearinghouse*** - Articles or webpages, including news coverage, about the Clearinghouse or describing Clearinghouse projects. ***Articles that use the Clearinghouse*** - Law review or other periodicals that cite entries in the Clearinghouse. ***Case Studies*** - A law review article, book, or other resource that discusses a case in the Clearinghouse. ***Clearinghouse Report*** - A white paper or report produced by the Clearinghouse.")
    cases: Optional[List[StrictStr]] = Field(default=None, description="The cases that are related to the resource. If the resource also has related case types, causes of action, issues, special collections, or attorney organizations, individual cases that all under those related items will not be part of cases.")
    case_types: Optional[List[StrictStr]] = Field(default=None, description="The case types that are related to the resource. For a full list of case types, see [case_types](https://api.clearinghouse.net/api-reference/objects/case/case-details#case_types).")
    var_date: Optional[StrictStr] = Field(default=None, description="The date a resource was created or published. The format of this string is \"YYYY-MM-DDThh:mm:ssTZ\". The time zone (TZ) will be either -5:00 for Eastern Standard Time or -4:00 for Eastern Daylight Time.", alias="date")
    causes: Optional[List[StrictStr]] = Field(default=None, description="The causes of action that are related to the resource. For a full list of causes of action, see [causes](https://api.clearinghouse.net/api-reference/objects/case/causes-of-action#causes).")
    issues: Optional[List[StrictStr]] = Field(default=None, description="The issues that are related to the resource. For a full list of issues, see [issues](https://api.clearinghouse.net/api-reference/objects/case/issues#issues).")
    special_collections: Optional[List[StrictStr]] = Field(default=None, description="The special collections that are related to the resource. For a full list of special collections, see [special_collections](https://api.clearinghouse.net/api-reference/objects/case/case-details#special_collections).")
    attorney_orgs: Optional[List[StrictStr]] = Field(default=None, description="The attorney organizations that are related to the resource. For a full list of attorney organizations, see [attorney_orgs](https://api.clearinghouse.net/api-reference/objects/case/parties#attorney_orgs).")
    source: Optional[StrictStr] = Field(default=None, description="For articles in law reviews or other periodicals, this field is the name of the publication. For websites, this field is the root of website.")
    __properties: ClassVar[List[str]] = ["file", "title", "author_role", "abstract", "author", "institution", "citation", "external_url", "display_date", "resource_type", "cases", "case_types", "date", "causes", "issues", "special_collections", "attorney_orgs", "source"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Resource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Resource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file": obj.get("file"),
            "title": obj.get("title"),
            "author_role": obj.get("author_role"),
            "abstract": obj.get("abstract"),
            "author": obj.get("author"),
            "institution": obj.get("institution"),
            "citation": obj.get("citation"),
            "external_url": obj.get("external_url"),
            "display_date": obj.get("display_date"),
            "resource_type": obj.get("resource_type"),
            "cases": obj.get("cases"),
            "case_types": obj.get("case_types"),
            "date": obj.get("date"),
            "causes": obj.get("causes"),
            "issues": obj.get("issues"),
            "special_collections": obj.get("special_collections"),
            "attorney_orgs": obj.get("attorney_orgs"),
            "source": obj.get("source")
        })
        return _obj


